### ISSUE TITLE
Failed to get encoded result

### ISSUE THREAD

**Issue by pnbao** [moono/stylegan2-encoder#1]
Hi @moono, 

Thanks for your great works!! 👍🏼  
I'm also looking for ways to encode images to StyleGAN2 latent space.
 
I have tried to use your encoding function but always got weird results.

Using encode_by_optimize_method.py script with test file: 
![canhhh](https://user-images.githubusercontent.com/11147999/91518213-b868de00-e92a-11ea-9e12-3cc783562093.png)

I have got a result as:
![image](https://user-images.githubusercontent.com/11147999/91518244-cb7bae00-e92a-11ea-937b-4310c5f9689b.png)

Am I missing anything? Thank yoy 😄

**Comment by moono** [comment]
well,
I just ran `encode_by_optimize_method.py` with your input image, and seems to be working.
Here is my result,
(since your input image is generated(fake) image, encoder works pretty well...)

on_w
![on_w_plus_test1 png_encoded](https://user-images.githubusercontent.com/6761398/91523637-3b446580-e938-11ea-8b53-4bfb332b69d6.png)

on_w_plus
![on_w_test1 png_encoded](https://user-images.githubusercontent.com/6761398/91523641-40a1b000-e938-11ea-8345-2d3b1a4655f6.png)

My best guess is that check your path to lpips checkpoint files,

**Comment by pnbao** [comment]
Thank @moono  for your prompt reply,

I have used the lpips checkpoint files from this repo also, do I need to update anything?

Moreover, I have created stylegan2 checkpoint convert using inference_from_official_weights.py script from your stylegan2-tf-2.x repo, is this correct? 

Then I ran encode_by_optimize_method.py script by this command: 

> python encode_by_optimize_method.py --is_on_w=True --lpips_ckpt_dir='/content/stylegan2-encoder/lpips' --images_dir='/content/stylegan2-encoder/test_images' --stylegan2_ckpt_dir='/content/stylegan2-tf-2.x/official-converted'


<img width="347" alt="Screen Shot 2020-08-28 at 15 47 15" src="https://user-images.githubusercontent.com/11147999/91530245-c24c0a80-e945-11ea-8920-9b76ecbd2f55.png">

**Comment by moono** [comment]
Hi, @pnbao 

> I have used the lpips checkpoint files from this repo also, do I need to update anything?

No, you did fine.

> Moreover, I have created stylegan2 checkpoint convert using inference_from_official_weights.py script from your stylegan2-tf-2.x repo, is this correct?

Yes. you're right about creating stylegan2 checkpoint(official_converted).

But, you should point the stylegan2 checkpoint to `--stylegan2_ckpt_dir='/content/stylegan2-tf-2.x/official-converted'/ref`, not `--stylegan2_ckpt_dir='/content/stylegan2-tf-2.x/official-converted'`

Also I use tensorflow version 2.0, just for your information.

**Comment by pnbao** [comment]
Its working now 😄 
Just replaced the checkpoint path to `official-converted/ref`, I didn't notice about that before.
Thank @moono for great support 💯 👍🏼
